
version: 2

jobs:
    checkout_code:
        docker:
            - image: circleci/golang:1.12.4
        steps:
            - checkout:
                path:  /go/src/github.com/dbgeek/twitter-bot1
            - run:
                name: list dir
                command: |
                    ls /go/src/github.com/dbgeek/twitter-bot1
            - run:
                name: pwd dir
                command: |
                    pwd
            - save_cache:
                key: v1-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - /go/src/github.com/dbgeek
    run_go_unit_tests:
        docker:
            - image: circleci/golang:1.12.4
        working_directory: /Users/bjorn.ahl/src/github.com/dbgeek/twitter-bot1/lambda/twitter-bot1/twitter-bot1
        environment:
            GO111MODULE: "on"
        steps:
            - restore_cache:
                key: v1-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: go install
                command: |
                    go install
            - run:
                name: run go unit tests
                command: |
                  go test -v 

workflows:
  version: 2
  build-and-deploy:
    jobs:
        - checkout_code
        - run_go_unit_tests
          requires:
                - checkout_code