version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
    checkout_code:
        docker:
            - image: circleci/golang:1.12.4
        steps:
            - checkout:
                path:  /go/src/github.com/dbgeek/twitter-bot1
            - save_cache:
                key: v1-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - /go/src/github.com/dbgeek
    run_go_unit_tests:
        docker:
            - image: circleci/golang:1.12.4
        working_directory: /go/src/github.com/dbgeek/twitter-bot1/lambda/twitter-bot1
        environment:
            GO111MODULE: "on"
        steps:
            - restore_cache:
                key: v1-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: install pip
                command: |
                    sudo apt-get install python-pip
            - aws-cli/install
            - aws-cli/configure
                aws-region: eu-north-1
            - run:
                name: show aws cli version
                command: |
                    aws --version
            - run:
                name: running go test
                command: |
                    make test-all
    awscli_dependencies:
        docker:
            - image: circleci/golang:1.12.4
        working_directory: ~/
        steps:
            - restore_cache:
                key: v1-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - restore_cache:
                key: awscli-{{ checksum "/go/src/github.com/dbgeek/twitter-bot1/.circleci/requirements.txt" }}
            - run:
                name: install pip
                command: |
                    sudo apt-get install python-pip
            - run:
                name: install virtualenv
                command: |
                    pip install virtualenv
            - run:
                name: setup dependencies
                command: |
                    python -m virtualenv awscli
                    . awscli/bin/activate
                    pip install -r /go/src/github.com/dbgeek/twitter-bot1/.circleci/requirements.txt
            - save_cache: # special step to save dependency cache
                key: awscli-{{ checksum "/go/src/github.com/dbgeek/twitter-bot1/.circleci/requirements.txt" }}
                paths:
                    - "awscli"

workflows:
  version: 2
  build-and-deploy:
    jobs:
        - checkout_code
        - run_go_unit_tests:
            context: aws
            requires:
              - checkout_code